services:
  database:
    image: "postgres:16.3"
    command: -c 'max_connections=200'
    ports:
      - "5432:5432"
    expose: 
      - "5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=password"
    hostname: postgres
    networks:
      - "backend-network"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    depends_on:
      database:
        condition: service_healthy
    build: .
    environment:
      - "PGPASSWORD=password"
    ports:
      - "9000:9000"
    networks:
      - "backend-network"

networks:
  backend-network:
    name: "backend-shared-network"
    driver: bridge
